# Generated by Django 4.0.3 on 2022-03-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=45)),
                ('password', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('kakao_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
