# Generated by Django 4.0.3 on 2022-03-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='planets',
            field=models.ManyToManyField(through='wishlists.WishList', to='planets.planet'),
        ),
    ]
