# Generated by Django 4.0.3 on 2022-03-19 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=45)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('min_of_people', models.PositiveIntegerField()),
                ('max_of_people', models.PositiveIntegerField()),
                ('num_of_bed', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'accomodations',
            },
        ),
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'galaxy',
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=45)),
                ('thumbnail', models.URLField(max_length=1000)),
                ('galaxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planets.galaxy')),
            ],
            options={
                'db_table': 'planets',
            },
        ),
        migrations.CreateModel(
            name='PlanetTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'planet_themes',
            },
        ),
        migrations.CreateModel(
            name='PlanetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planets.planet')),
            ],
            options={
                'db_table': 'planet_images',
            },
        ),
        migrations.AddField(
            model_name='planet',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planets.planettheme'),
        ),
        migrations.CreateModel(
            name='AccomodationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000)),
                ('accomodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planets.accomodation')),
            ],
            options={
                'db_table': 'accomodation_images',
            },
        ),
        migrations.AddField(
            model_name='accomodation',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planets.planet'),
        ),
    ]
